/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const SubscriptionPlan = IDL.Variant({
  'pro' : IDL.Null,
  'premium' : IDL.Null,
  'basic' : IDL.Null,
});
export const Time = IDL.Int;
export const Discount = IDL.Record({
  'id' : IDL.Nat,
  'code' : IDL.Text,
  'enabled' : IDL.Bool,
  'percentage' : IDL.Float64,
  'validUntil' : Time,
});
export const PaymentMethod = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'enabled' : IDL.Bool,
});
export const PendingPayment = IDL.Record({
  'couponCode' : IDL.Opt(IDL.Text),
  'finalAmount' : IDL.Nat,
  'plan' : SubscriptionPlan,
  'user' : IDL.Principal,
  'submittedAt' : Time,
  'fileSize' : IDL.Nat,
  'fileType' : IDL.Text,
  'paymentProof' : IDL.Vec(IDL.Nat8),
  'pointsRedeemed' : IDL.Nat,
  'transactionId' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MistakeCategory = IDL.Variant({
  'tradeTiming' : IDL.Null,
  'positionSizing' : IDL.Null,
  'riskManagement' : IDL.Null,
  'emotionalControl' : IDL.Null,
  'overtrading' : IDL.Null,
});
export const Suggestion = IDL.Record({
  'suggestion' : IDL.Text,
  'category' : IDL.Text,
});
export const MistakeEntry = IDL.Record({
  'id' : IDL.Nat,
  'tradeDate' : Time,
  'description' : IDL.Text,
  'suggestion' : Suggestion,
  'category' : MistakeCategory,
});
export const TradeEntry = IDL.Record({
  'tradeDate' : Time,
  'riskAmount' : IDL.Float64,
  'takeProfit' : IDL.Float64,
  'riskReward' : IDL.Float64,
  'session' : IDL.Text,
  'stopLoss' : IDL.Float64,
  'tradingPair' : IDL.Text,
  'outcome' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'dateJoined' : Time,
  'userId' : IDL.Nat,
  'fullName' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const SubscriptionState = IDL.Record({
  'trialActive' : IDL.Bool,
  'paidStart' : IDL.Opt(Time),
  'plan' : IDL.Opt(SubscriptionPlan),
  'trialStart' : Time,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminActivateSubscription' : IDL.Func(
      [IDL.Principal, SubscriptionPlan],
      [],
      [],
    ),
  'adminCancelSubscription' : IDL.Func([IDL.Principal], [], []),
  'adminCreateDiscount' : IDL.Func(
      [IDL.Text, IDL.Float64, Time],
      [Discount],
      [],
    ),
  'adminCreatePaymentMethod' : IDL.Func(
      [IDL.Text, IDL.Text],
      [PaymentMethod],
      [],
    ),
  'adminDeleteDiscount' : IDL.Func([IDL.Nat], [], []),
  'adminDeletePaymentMethod' : IDL.Func([IDL.Nat], [], []),
  'adminDeletePaymentProof' : IDL.Func([IDL.Principal], [], []),
  'adminGetAllDiscounts' : IDL.Func([], [IDL.Vec(Discount)], ['query']),
  'adminGetAllPaymentMethods' : IDL.Func(
      [],
      [IDL.Vec(PaymentMethod)],
      ['query'],
    ),
  'adminGetPaymentProof' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  'adminGetPendingPayments' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, PendingPayment))],
      ['query'],
    ),
  'adminRejectPayment' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'adminRemoveUser' : IDL.Func([IDL.Principal], [], []),
  'adminReviewAndApprovePayment' : IDL.Func([IDL.Principal], [], []),
  'adminSetUnlockPassword' : IDL.Func([IDL.Text], [], []),
  'adminUpdateDiscount' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Float64, Time, IDL.Bool],
      [],
      [],
    ),
  'adminUpdatePaymentMethod' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelTrial' : IDL.Func([], [], []),
  'clearPaymentQRCode' : IDL.Func([], [], []),
  'createMistakeEntry' : IDL.Func(
      [MistakeCategory, IDL.Text, Time],
      [MistakeEntry],
      [],
    ),
  'createTradeEntry' : IDL.Func(
      [
        Time,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Bool,
      ],
      [TradeEntry],
      [],
    ),
  'createUserProfile' : IDL.Func([IDL.Text, IDL.Text], [UserProfile], []),
  'deleteMistakeEntry' : IDL.Func([IDL.Nat], [], []),
  'deleteTradeEntry' : IDL.Func([IDL.Nat], [], []),
  'ensureHasUserAndGetPaymentQRCode' : IDL.Func(
      [],
      [IDL.Opt(ExternalBlob)],
      ['query'],
    ),
  'ensureHasUserAndGetSubscriptionState' : IDL.Func(
      [],
      [IDL.Opt(SubscriptionState)],
      ['query'],
    ),
  'findUserById' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getActiveDiscounts' : IDL.Func([], [IDL.Vec(Discount)], ['query']),
  'getAllMistakes' : IDL.Func([], [IDL.Vec(MistakeEntry)], ['query']),
  'getAllTradeDates' : IDL.Func([], [IDL.Vec(Time)], ['query']),
  'getAllTrades' : IDL.Func([], [IDL.Vec(TradeEntry)], ['query']),
  'getAllUserData' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Tuple(
            IDL.Principal,
            UserProfile,
            IDL.Vec(TradeEntry),
            IDL.Vec(MistakeEntry),
            IDL.Opt(SubscriptionState),
          )
        ),
      ],
      ['query'],
    ),
  'getAllUsersWithIds' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getAnalytics' : IDL.Func(
      [IDL.Opt(Time), IDL.Opt(Time)],
      [
        IDL.Record({
          'totalTrades' : IDL.Nat,
          'grossProfit' : IDL.Float64,
          'totalPL' : IDL.Float64,
          'losingTrades' : IDL.Nat,
          'winningTrades' : IDL.Nat,
          'grossLoss' : IDL.Float64,
          'accuracy' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getCallerPlan' : IDL.Func(
      [],
      [
        IDL.Opt(
          IDL.Variant({
            'trial' : IDL.Null,
            'expired' : IDL.Null,
            'paid' : SubscriptionPlan,
          })
        ),
      ],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyProfitForDate' : IDL.Func([Time], [IDL.Float64], ['query']),
  'getEnabledPaymentMethods' : IDL.Func(
      [],
      [IDL.Vec(PaymentMethod)],
      ['query'],
    ),
  'getTradesByDateRange' : IDL.Func(
      [Time, Time],
      [IDL.Vec(TradeEntry)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'grantAdminRole' : IDL.Func([IDL.Principal], [], []),
  'healthCheck' : IDL.Func([], [IDL.Text], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isLockedAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isUserRegistered' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'revokeAdminRole' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitPaymentForSubscription' : IDL.Func(
      [
        SubscriptionPlan,
        IDL.Opt(IDL.Text),
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Vec(IDL.Nat8),
      ],
      [],
      [],
    ),
  'unlockAdmin' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'updateMistakeEntry' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateTradeEntry' : IDL.Func([IDL.Nat, TradeEntry], [], []),
  'uploadPaymentQRCode' : IDL.Func([ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const SubscriptionPlan = IDL.Variant({
    'pro' : IDL.Null,
    'premium' : IDL.Null,
    'basic' : IDL.Null,
  });
  const Time = IDL.Int;
  const Discount = IDL.Record({
    'id' : IDL.Nat,
    'code' : IDL.Text,
    'enabled' : IDL.Bool,
    'percentage' : IDL.Float64,
    'validUntil' : Time,
  });
  const PaymentMethod = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'enabled' : IDL.Bool,
  });
  const PendingPayment = IDL.Record({
    'couponCode' : IDL.Opt(IDL.Text),
    'finalAmount' : IDL.Nat,
    'plan' : SubscriptionPlan,
    'user' : IDL.Principal,
    'submittedAt' : Time,
    'fileSize' : IDL.Nat,
    'fileType' : IDL.Text,
    'paymentProof' : IDL.Vec(IDL.Nat8),
    'pointsRedeemed' : IDL.Nat,
    'transactionId' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MistakeCategory = IDL.Variant({
    'tradeTiming' : IDL.Null,
    'positionSizing' : IDL.Null,
    'riskManagement' : IDL.Null,
    'emotionalControl' : IDL.Null,
    'overtrading' : IDL.Null,
  });
  const Suggestion = IDL.Record({
    'suggestion' : IDL.Text,
    'category' : IDL.Text,
  });
  const MistakeEntry = IDL.Record({
    'id' : IDL.Nat,
    'tradeDate' : Time,
    'description' : IDL.Text,
    'suggestion' : Suggestion,
    'category' : MistakeCategory,
  });
  const TradeEntry = IDL.Record({
    'tradeDate' : Time,
    'riskAmount' : IDL.Float64,
    'takeProfit' : IDL.Float64,
    'riskReward' : IDL.Float64,
    'session' : IDL.Text,
    'stopLoss' : IDL.Float64,
    'tradingPair' : IDL.Text,
    'outcome' : IDL.Bool,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'dateJoined' : Time,
    'userId' : IDL.Nat,
    'fullName' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const SubscriptionState = IDL.Record({
    'trialActive' : IDL.Bool,
    'paidStart' : IDL.Opt(Time),
    'plan' : IDL.Opt(SubscriptionPlan),
    'trialStart' : Time,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminActivateSubscription' : IDL.Func(
        [IDL.Principal, SubscriptionPlan],
        [],
        [],
      ),
    'adminCancelSubscription' : IDL.Func([IDL.Principal], [], []),
    'adminCreateDiscount' : IDL.Func(
        [IDL.Text, IDL.Float64, Time],
        [Discount],
        [],
      ),
    'adminCreatePaymentMethod' : IDL.Func(
        [IDL.Text, IDL.Text],
        [PaymentMethod],
        [],
      ),
    'adminDeleteDiscount' : IDL.Func([IDL.Nat], [], []),
    'adminDeletePaymentMethod' : IDL.Func([IDL.Nat], [], []),
    'adminDeletePaymentProof' : IDL.Func([IDL.Principal], [], []),
    'adminGetAllDiscounts' : IDL.Func([], [IDL.Vec(Discount)], ['query']),
    'adminGetAllPaymentMethods' : IDL.Func(
        [],
        [IDL.Vec(PaymentMethod)],
        ['query'],
      ),
    'adminGetPaymentProof' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    'adminGetPendingPayments' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, PendingPayment))],
        ['query'],
      ),
    'adminRejectPayment' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'adminRemoveUser' : IDL.Func([IDL.Principal], [], []),
    'adminReviewAndApprovePayment' : IDL.Func([IDL.Principal], [], []),
    'adminSetUnlockPassword' : IDL.Func([IDL.Text], [], []),
    'adminUpdateDiscount' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Float64, Time, IDL.Bool],
        [],
        [],
      ),
    'adminUpdatePaymentMethod' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelTrial' : IDL.Func([], [], []),
    'clearPaymentQRCode' : IDL.Func([], [], []),
    'createMistakeEntry' : IDL.Func(
        [MistakeCategory, IDL.Text, Time],
        [MistakeEntry],
        [],
      ),
    'createTradeEntry' : IDL.Func(
        [
          Time,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Bool,
        ],
        [TradeEntry],
        [],
      ),
    'createUserProfile' : IDL.Func([IDL.Text, IDL.Text], [UserProfile], []),
    'deleteMistakeEntry' : IDL.Func([IDL.Nat], [], []),
    'deleteTradeEntry' : IDL.Func([IDL.Nat], [], []),
    'ensureHasUserAndGetPaymentQRCode' : IDL.Func(
        [],
        [IDL.Opt(ExternalBlob)],
        ['query'],
      ),
    'ensureHasUserAndGetSubscriptionState' : IDL.Func(
        [],
        [IDL.Opt(SubscriptionState)],
        ['query'],
      ),
    'findUserById' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getActiveDiscounts' : IDL.Func([], [IDL.Vec(Discount)], ['query']),
    'getAllMistakes' : IDL.Func([], [IDL.Vec(MistakeEntry)], ['query']),
    'getAllTradeDates' : IDL.Func([], [IDL.Vec(Time)], ['query']),
    'getAllTrades' : IDL.Func([], [IDL.Vec(TradeEntry)], ['query']),
    'getAllUserData' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Tuple(
              IDL.Principal,
              UserProfile,
              IDL.Vec(TradeEntry),
              IDL.Vec(MistakeEntry),
              IDL.Opt(SubscriptionState),
            )
          ),
        ],
        ['query'],
      ),
    'getAllUsersWithIds' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getAnalytics' : IDL.Func(
        [IDL.Opt(Time), IDL.Opt(Time)],
        [
          IDL.Record({
            'totalTrades' : IDL.Nat,
            'grossProfit' : IDL.Float64,
            'totalPL' : IDL.Float64,
            'losingTrades' : IDL.Nat,
            'winningTrades' : IDL.Nat,
            'grossLoss' : IDL.Float64,
            'accuracy' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getCallerPlan' : IDL.Func(
        [],
        [
          IDL.Opt(
            IDL.Variant({
              'trial' : IDL.Null,
              'expired' : IDL.Null,
              'paid' : SubscriptionPlan,
            })
          ),
        ],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyProfitForDate' : IDL.Func([Time], [IDL.Float64], ['query']),
    'getEnabledPaymentMethods' : IDL.Func(
        [],
        [IDL.Vec(PaymentMethod)],
        ['query'],
      ),
    'getTradesByDateRange' : IDL.Func(
        [Time, Time],
        [IDL.Vec(TradeEntry)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'grantAdminRole' : IDL.Func([IDL.Principal], [], []),
    'healthCheck' : IDL.Func([], [IDL.Text], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isLockedAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isUserRegistered' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'revokeAdminRole' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitPaymentForSubscription' : IDL.Func(
        [
          SubscriptionPlan,
          IDL.Opt(IDL.Text),
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Vec(IDL.Nat8),
        ],
        [],
        [],
      ),
    'unlockAdmin' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'updateMistakeEntry' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateTradeEntry' : IDL.Func([IDL.Nat, TradeEntry], [], []),
    'uploadPaymentQRCode' : IDL.Func([ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };