/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Discount {
  'id' : bigint,
  'code' : string,
  'enabled' : boolean,
  'percentage' : number,
  'validUntil' : Time,
}
export type ExternalBlob = Uint8Array;
export type MistakeCategory = { 'tradeTiming' : null } |
  { 'positionSizing' : null } |
  { 'riskManagement' : null } |
  { 'emotionalControl' : null } |
  { 'overtrading' : null };
export interface MistakeEntry {
  'id' : bigint,
  'tradeDate' : Time,
  'description' : string,
  'suggestion' : Suggestion,
  'category' : MistakeCategory,
}
export interface PaymentMethod {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'enabled' : boolean,
}
export interface PendingPayment {
  'couponCode' : [] | [string],
  'finalAmount' : bigint,
  'plan' : SubscriptionPlan,
  'user' : Principal,
  'submittedAt' : Time,
  'fileSize' : bigint,
  'fileType' : string,
  'paymentProof' : Uint8Array,
  'pointsRedeemed' : bigint,
  'transactionId' : string,
}
export type SubscriptionPlan = { 'pro' : null } |
  { 'premium' : null } |
  { 'basic' : null };
export interface SubscriptionState {
  'trialActive' : boolean,
  'paidStart' : [] | [Time],
  'plan' : [] | [SubscriptionPlan],
  'trialStart' : Time,
}
export interface Suggestion { 'suggestion' : string, 'category' : string }
export type Time = bigint;
export interface TradeEntry {
  'tradeDate' : Time,
  'riskAmount' : number,
  'takeProfit' : number,
  'riskReward' : number,
  'session' : string,
  'stopLoss' : number,
  'tradingPair' : string,
  'outcome' : boolean,
}
export interface UserProfile {
  'username' : string,
  'dateJoined' : Time,
  'userId' : bigint,
  'fullName' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminActivateSubscription' : ActorMethod<
    [Principal, SubscriptionPlan],
    undefined
  >,
  'adminCancelSubscription' : ActorMethod<[Principal], undefined>,
  'adminCreateDiscount' : ActorMethod<[string, number, Time], Discount>,
  'adminCreatePaymentMethod' : ActorMethod<[string, string], PaymentMethod>,
  'adminDeleteDiscount' : ActorMethod<[bigint], undefined>,
  'adminDeletePaymentMethod' : ActorMethod<[bigint], undefined>,
  'adminDeletePaymentProof' : ActorMethod<[Principal], undefined>,
  'adminGetAllDiscounts' : ActorMethod<[], Array<Discount>>,
  'adminGetAllPaymentMethods' : ActorMethod<[], Array<PaymentMethod>>,
  'adminGetPaymentProof' : ActorMethod<[Principal], [] | [Uint8Array]>,
  'adminGetPendingPayments' : ActorMethod<
    [],
    Array<[Principal, PendingPayment]>
  >,
  'adminRejectPayment' : ActorMethod<[Principal, string], undefined>,
  'adminRemoveUser' : ActorMethod<[Principal], undefined>,
  'adminReviewAndApprovePayment' : ActorMethod<[Principal], undefined>,
  'adminSetUnlockPassword' : ActorMethod<[string], undefined>,
  'adminUpdateDiscount' : ActorMethod<
    [bigint, string, number, Time, boolean],
    undefined
  >,
  'adminUpdatePaymentMethod' : ActorMethod<
    [bigint, string, string, boolean],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelTrial' : ActorMethod<[], undefined>,
  'clearPaymentQRCode' : ActorMethod<[], undefined>,
  'createMistakeEntry' : ActorMethod<
    [MistakeCategory, string, Time],
    MistakeEntry
  >,
  'createTradeEntry' : ActorMethod<
    [Time, string, string, number, number, number, number, boolean],
    TradeEntry
  >,
  'createUserProfile' : ActorMethod<[string, string], UserProfile>,
  'deleteMistakeEntry' : ActorMethod<[bigint], undefined>,
  'deleteTradeEntry' : ActorMethod<[bigint], undefined>,
  'ensureHasUserAndGetPaymentQRCode' : ActorMethod<[], [] | [ExternalBlob]>,
  'ensureHasUserAndGetSubscriptionState' : ActorMethod<
    [],
    [] | [SubscriptionState]
  >,
  'findUserById' : ActorMethod<[bigint], [] | [[Principal, UserProfile]]>,
  'getActiveDiscounts' : ActorMethod<[], Array<Discount>>,
  'getAllMistakes' : ActorMethod<[], Array<MistakeEntry>>,
  'getAllTradeDates' : ActorMethod<[], Array<Time>>,
  'getAllTrades' : ActorMethod<[], Array<TradeEntry>>,
  'getAllUserData' : ActorMethod<
    [],
    Array<
      [
        Principal,
        UserProfile,
        Array<TradeEntry>,
        Array<MistakeEntry>,
        [] | [SubscriptionState],
      ]
    >
  >,
  'getAllUsersWithIds' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getAnalytics' : ActorMethod<
    [[] | [Time], [] | [Time]],
    {
      'totalTrades' : bigint,
      'grossProfit' : number,
      'totalPL' : number,
      'losingTrades' : bigint,
      'winningTrades' : bigint,
      'grossLoss' : number,
      'accuracy' : number,
    }
  >,
  'getCallerPlan' : ActorMethod<
    [],
    [] | [
      { 'trial' : null } |
        { 'expired' : null } |
        { 'paid' : SubscriptionPlan }
    ]
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailyProfitForDate' : ActorMethod<[Time], number>,
  'getEnabledPaymentMethods' : ActorMethod<[], Array<PaymentMethod>>,
  'getTradesByDateRange' : ActorMethod<[Time, Time], Array<TradeEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'grantAdminRole' : ActorMethod<[Principal], undefined>,
  'healthCheck' : ActorMethod<[], string>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isLockedAdmin' : ActorMethod<[], boolean>,
  'isUserRegistered' : ActorMethod<[Principal], boolean>,
  'revokeAdminRole' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitPaymentForSubscription' : ActorMethod<
    [
      SubscriptionPlan,
      [] | [string],
      bigint,
      bigint,
      string,
      string,
      bigint,
      Uint8Array,
    ],
    undefined
  >,
  'unlockAdmin' : ActorMethod<[string], boolean>,
  'updateMistakeEntry' : ActorMethod<[bigint, string], undefined>,
  'updateTradeEntry' : ActorMethod<[bigint, TradeEntry], undefined>,
  'uploadPaymentQRCode' : ActorMethod<[ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];