/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SubscriptionState {
    trialActive: boolean;
    paidStart?: Time;
    plan?: SubscriptionPlan;
    trialStart: Time;
}
export interface PendingPayment {
    couponCode?: string;
    finalAmount: bigint;
    plan: SubscriptionPlan;
    user: Principal;
    submittedAt: Time;
    fileSize: bigint;
    fileType: string;
    paymentProof: Uint8Array;
    pointsRedeemed: bigint;
    transactionId: string;
}
export type Time = bigint;
export interface Discount {
    id: bigint;
    code: string;
    enabled: boolean;
    percentage: number;
    validUntil: Time;
}
export interface PaymentMethod {
    id: bigint;
    name: string;
    description: string;
    enabled: boolean;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Suggestion {
    suggestion: string;
    category: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface TradeEntry {
    tradeDate: Time;
    riskAmount: number;
    takeProfit: number;
    riskReward: number;
    session: string;
    stopLoss: number;
    tradingPair: string;
    outcome: boolean;
}
export interface MistakeEntry {
    id: bigint;
    tradeDate: Time;
    description: string;
    suggestion: Suggestion;
    category: MistakeCategory;
}
export interface UserProfile {
    username: string;
    dateJoined: Time;
    userId: bigint;
    fullName: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum MistakeCategory {
    tradeTiming = "tradeTiming",
    positionSizing = "positionSizing",
    riskManagement = "riskManagement",
    emotionalControl = "emotionalControl",
    overtrading = "overtrading"
}
export enum SubscriptionPlan {
    pro = "pro",
    premium = "premium",
    basic = "basic"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    adminActivateSubscription(user: Principal, plan: SubscriptionPlan): Promise<void>;
    adminCancelSubscription(user: Principal): Promise<void>;
    adminCreateDiscount(code: string, percentage: number, validUntil: Time): Promise<Discount>;
    adminCreatePaymentMethod(name: string, description: string): Promise<PaymentMethod>;
    adminDeleteDiscount(id: bigint): Promise<void>;
    adminDeletePaymentMethod(id: bigint): Promise<void>;
    adminDeletePaymentProof(user: Principal): Promise<void>;
    adminGetAllDiscounts(): Promise<Array<Discount>>;
    adminGetAllPaymentMethods(): Promise<Array<PaymentMethod>>;
    adminGetPaymentProof(user: Principal): Promise<Uint8Array | null>;
    adminGetPendingPayments(): Promise<Array<[Principal, PendingPayment]>>;
    adminRejectPayment(user: Principal, reason: string): Promise<void>;
    adminRemoveUser(user: Principal): Promise<void>;
    adminReviewAndApprovePayment(user: Principal): Promise<void>;
    adminSetUnlockPassword(newPassword: string): Promise<void>;
    adminUpdateDiscount(id: bigint, code: string, percentage: number, validUntil: Time, enabled: boolean): Promise<void>;
    adminUpdatePaymentMethod(id: bigint, name: string, description: string, enabled: boolean): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cancelTrial(): Promise<void>;
    clearPaymentQRCode(): Promise<void>;
    createMistakeEntry(category: MistakeCategory, description: string, tradeDate: Time): Promise<MistakeEntry>;
    createTradeEntry(tradeDate: Time, session: string, tradingPair: string, stopLoss: number, takeProfit: number, riskReward: number, riskAmount: number, outcome: boolean): Promise<TradeEntry>;
    createUserProfile(fullName: string, username: string): Promise<UserProfile>;
    deleteMistakeEntry(mistakeId: bigint): Promise<void>;
    deleteTradeEntry(index: bigint): Promise<void>;
    findUserById(targetId: bigint): Promise<[Principal, UserProfile] | null>;
    getActiveDiscounts(): Promise<Array<Discount>>;
    getAllMistakes(): Promise<Array<MistakeEntry>>;
    getAllTradeDates(): Promise<Array<Time>>;
    getAllTrades(): Promise<Array<TradeEntry>>;
    getAllUserData(): Promise<Array<[Principal, UserProfile, Array<TradeEntry>, Array<MistakeEntry>, SubscriptionState | null]>>;
    getAllUsersWithIds(): Promise<Array<[Principal, UserProfile]>>;
    getAnalytics(startDate: Time | null, endDate: Time | null): Promise<{
        totalTrades: bigint;
        grossProfit: number;
        totalPL: number;
        losingTrades: bigint;
        winningTrades: bigint;
        grossLoss: number;
        accuracy: number;
    }>;
    getCallerPlan(): Promise<{
        __kind__: "trial";
        trial: null;
    } | {
        __kind__: "expired";
        expired: null;
    } | {
        __kind__: "paid";
        paid: SubscriptionPlan;
    } | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDailyProfitForDate(date: Time): Promise<number>;
    getEnabledPaymentMethods(): Promise<Array<PaymentMethod>>;
    getPaymentQRCode(): Promise<ExternalBlob | null>;
    getSubscriptionState(): Promise<SubscriptionState | null>;
    getTradesByDateRange(startDate: Time, endDate: Time): Promise<Array<TradeEntry>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    grantAdminRole(target: Principal): Promise<void>;
    healthCheck(): Promise<string>;
    isCallerAdmin(): Promise<boolean>;
    isLockedAdmin(): Promise<boolean>;
    isUserRegistered(user: Principal): Promise<boolean>;
    revokeAdminRole(target: Principal): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitPaymentForSubscription(plan: SubscriptionPlan, couponCode: string | null, pointsRedeemed: bigint, finalAmount: bigint, transactionId: string, fileType: string, fileSize: bigint, paymentProof: Uint8Array): Promise<void>;
    unlockAdmin(password: string): Promise<boolean>;
    updateMistakeEntry(mistakeId: bigint, description: string): Promise<void>;
    updateTradeEntry(index: bigint, entry: TradeEntry): Promise<void>;
    uploadPaymentQRCode(blob: ExternalBlob): Promise<void>;
}
import type { ExternalBlob as _ExternalBlob, MistakeCategory as _MistakeCategory, MistakeEntry as _MistakeEntry, PendingPayment as _PendingPayment, SubscriptionPlan as _SubscriptionPlan, SubscriptionState as _SubscriptionState, Suggestion as _Suggestion, Time as _Time, TradeEntry as _TradeEntry, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async adminActivateSubscription(arg0: Principal, arg1: SubscriptionPlan): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminActivateSubscription(arg0, to_candid_SubscriptionPlan_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminActivateSubscription(arg0, to_candid_SubscriptionPlan_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async adminCancelSubscription(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCancelSubscription(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCancelSubscription(arg0);
            return result;
        }
    }
    async adminCreateDiscount(arg0: string, arg1: number, arg2: Time): Promise<Discount> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCreateDiscount(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCreateDiscount(arg0, arg1, arg2);
            return result;
        }
    }
    async adminCreatePaymentMethod(arg0: string, arg1: string): Promise<PaymentMethod> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCreatePaymentMethod(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCreatePaymentMethod(arg0, arg1);
            return result;
        }
    }
    async adminDeleteDiscount(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteDiscount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteDiscount(arg0);
            return result;
        }
    }
    async adminDeletePaymentMethod(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeletePaymentMethod(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeletePaymentMethod(arg0);
            return result;
        }
    }
    async adminDeletePaymentProof(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeletePaymentProof(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeletePaymentProof(arg0);
            return result;
        }
    }
    async adminGetAllDiscounts(): Promise<Array<Discount>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllDiscounts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllDiscounts();
            return result;
        }
    }
    async adminGetAllPaymentMethods(): Promise<Array<PaymentMethod>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllPaymentMethods();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllPaymentMethods();
            return result;
        }
    }
    async adminGetPaymentProof(arg0: Principal): Promise<Uint8Array | null> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetPaymentProof(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetPaymentProof(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetPendingPayments(): Promise<Array<[Principal, PendingPayment]>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetPendingPayments();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetPendingPayments();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminRejectPayment(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminRejectPayment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminRejectPayment(arg0, arg1);
            return result;
        }
    }
    async adminRemoveUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminRemoveUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminRemoveUser(arg0);
            return result;
        }
    }
    async adminReviewAndApprovePayment(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminReviewAndApprovePayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminReviewAndApprovePayment(arg0);
            return result;
        }
    }
    async adminSetUnlockPassword(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSetUnlockPassword(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSetUnlockPassword(arg0);
            return result;
        }
    }
    async adminUpdateDiscount(arg0: bigint, arg1: string, arg2: number, arg3: Time, arg4: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateDiscount(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateDiscount(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async adminUpdatePaymentMethod(arg0: bigint, arg1: string, arg2: string, arg3: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdatePaymentMethod(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdatePaymentMethod(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n18(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n18(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelTrial(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelTrial();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelTrial();
            return result;
        }
    }
    async clearPaymentQRCode(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearPaymentQRCode();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearPaymentQRCode();
            return result;
        }
    }
    async createMistakeEntry(arg0: MistakeCategory, arg1: string, arg2: Time): Promise<MistakeEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.createMistakeEntry(to_candid_MistakeCategory_n20(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return from_candid_MistakeEntry_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMistakeEntry(to_candid_MistakeCategory_n20(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return from_candid_MistakeEntry_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async createTradeEntry(arg0: Time, arg1: string, arg2: string, arg3: number, arg4: number, arg5: number, arg6: number, arg7: boolean): Promise<TradeEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.createTradeEntry(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTradeEntry(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async createUserProfile(arg0: string, arg1: string): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.createUserProfile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUserProfile(arg0, arg1);
            return result;
        }
    }
    async deleteMistakeEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMistakeEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMistakeEntry(arg0);
            return result;
        }
    }
    async deleteTradeEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTradeEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTradeEntry(arg0);
            return result;
        }
    }
    async findUserById(arg0: bigint): Promise<[Principal, UserProfile] | null> {
        if (this.processError) {
            try {
                const result = await this.actor.findUserById(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findUserById(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActiveDiscounts(): Promise<Array<Discount>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveDiscounts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveDiscounts();
            return result;
        }
    }
    async getAllMistakes(): Promise<Array<MistakeEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMistakes();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMistakes();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTradeDates(): Promise<Array<Time>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTradeDates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTradeDates();
            return result;
        }
    }
    async getAllTrades(): Promise<Array<TradeEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTrades();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTrades();
            return result;
        }
    }
    async getAllUserData(): Promise<Array<[Principal, UserProfile, Array<TradeEntry>, Array<MistakeEntry>, SubscriptionState | null]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserData();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserData();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsersWithIds(): Promise<Array<[Principal, UserProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsersWithIds();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsersWithIds();
            return result;
        }
    }
    async getAnalytics(arg0: Time | null, arg1: Time | null): Promise<{
        totalTrades: bigint;
        grossProfit: number;
        totalPL: number;
        losingTrades: bigint;
        winningTrades: bigint;
        grossLoss: number;
        accuracy: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalytics(to_candid_opt_n35(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n35(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalytics(to_candid_opt_n35(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n35(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getCallerPlan(): Promise<{
        __kind__: "trial";
        trial: null;
    } | {
        __kind__: "expired";
        expired: null;
    } | {
        __kind__: "paid";
        paid: SubscriptionPlan;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerPlan();
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerPlan();
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailyProfitForDate(arg0: Time): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyProfitForDate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyProfitForDate(arg0);
            return result;
        }
    }
    async getEnabledPaymentMethods(): Promise<Array<PaymentMethod>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEnabledPaymentMethods();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEnabledPaymentMethods();
            return result;
        }
    }
    async getPaymentQRCode(): Promise<ExternalBlob | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentQRCode();
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentQRCode();
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubscriptionState(): Promise<SubscriptionState | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubscriptionState();
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubscriptionState();
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTradesByDateRange(arg0: Time, arg1: Time): Promise<Array<TradeEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTradesByDateRange(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTradesByDateRange(arg0, arg1);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async grantAdminRole(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.grantAdminRole(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.grantAdminRole(arg0);
            return result;
        }
    }
    async healthCheck(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.healthCheck();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.healthCheck();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isLockedAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isLockedAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isLockedAdmin();
            return result;
        }
    }
    async isUserRegistered(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isUserRegistered(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isUserRegistered(arg0);
            return result;
        }
    }
    async revokeAdminRole(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.revokeAdminRole(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revokeAdminRole(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitPaymentForSubscription(arg0: SubscriptionPlan, arg1: string | null, arg2: bigint, arg3: bigint, arg4: string, arg5: string, arg6: bigint, arg7: Uint8Array): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitPaymentForSubscription(to_candid_SubscriptionPlan_n8(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n43(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitPaymentForSubscription(to_candid_SubscriptionPlan_n8(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n43(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async unlockAdmin(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.unlockAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlockAdmin(arg0);
            return result;
        }
    }
    async updateMistakeEntry(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMistakeEntry(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMistakeEntry(arg0, arg1);
            return result;
        }
    }
    async updateTradeEntry(arg0: bigint, arg1: TradeEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTradeEntry(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTradeEntry(arg0, arg1);
            return result;
        }
    }
    async uploadPaymentQRCode(arg0: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadPaymentQRCode(await to_candid_ExternalBlob_n44(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadPaymentQRCode(await to_candid_ExternalBlob_n44(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_MistakeCategory_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MistakeCategory): MistakeCategory {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_MistakeEntry_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MistakeEntry): MistakeEntry {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_PendingPayment_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PendingPayment): PendingPayment {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionPlan_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionPlan): SubscriptionPlan {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionState_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionState): SubscriptionState {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Uint8Array]): Uint8Array | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [[Principal, _UserProfile]]): [Principal, UserProfile] | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SubscriptionState]): SubscriptionState | null {
    return value.length === 0 ? null : from_candid_SubscriptionState_n31(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SubscriptionPlan]): SubscriptionPlan | null {
    return value.length === 0 ? null : from_candid_SubscriptionPlan_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        trial: null;
    } | {
        expired: null;
    } | {
        paid: _SubscriptionPlan;
    }]): {
    __kind__: "trial";
    trial: null;
} | {
    __kind__: "expired";
    expired: null;
} | {
    __kind__: "paid";
    paid: SubscriptionPlan;
} | null {
    return value.length === 0 ? null : from_candid_variant_n37(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n42(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    couponCode: [] | [string];
    finalAmount: bigint;
    plan: _SubscriptionPlan;
    user: Principal;
    submittedAt: _Time;
    fileSize: bigint;
    fileType: string;
    paymentProof: Uint8Array;
    pointsRedeemed: bigint;
    transactionId: string;
}): {
    couponCode?: string;
    finalAmount: bigint;
    plan: SubscriptionPlan;
    user: Principal;
    submittedAt: Time;
    fileSize: bigint;
    fileType: string;
    paymentProof: Uint8Array;
    pointsRedeemed: bigint;
    transactionId: string;
} {
    return {
        couponCode: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.couponCode)),
        finalAmount: value.finalAmount,
        plan: from_candid_SubscriptionPlan_n16(_uploadFile, _downloadFile, value.plan),
        user: value.user,
        submittedAt: value.submittedAt,
        fileSize: value.fileSize,
        fileType: value.fileType,
        paymentProof: value.paymentProof,
        pointsRedeemed: value.pointsRedeemed,
        transactionId: value.transactionId
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    tradeDate: _Time;
    description: string;
    suggestion: _Suggestion;
    category: _MistakeCategory;
}): {
    id: bigint;
    tradeDate: Time;
    description: string;
    suggestion: Suggestion;
    category: MistakeCategory;
} {
    return {
        id: value.id,
        tradeDate: value.tradeDate,
        description: value.description,
        suggestion: value.suggestion,
        category: from_candid_MistakeCategory_n24(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    trialActive: boolean;
    paidStart: [] | [_Time];
    plan: [] | [_SubscriptionPlan];
    trialStart: _Time;
}): {
    trialActive: boolean;
    paidStart?: Time;
    plan?: SubscriptionPlan;
    trialStart: Time;
} {
    return {
        trialActive: value.trialActive,
        paidStart: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.paidStart)),
        plan: record_opt_to_undefined(from_candid_opt_n34(_uploadFile, _downloadFile, value.plan)),
        trialStart: value.trialStart
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_tuple_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _PendingPayment]): [Principal, PendingPayment] {
    return [
        value[0],
        from_candid_PendingPayment_n13(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _UserProfile, Array<_TradeEntry>, Array<_MistakeEntry>, [] | [_SubscriptionState]]): [Principal, UserProfile, Array<TradeEntry>, Array<MistakeEntry>, SubscriptionState | null] {
    return [
        value[0],
        value[1],
        value[2],
        from_candid_vec_n27(_uploadFile, _downloadFile, value[3]),
        from_candid_opt_n30(_uploadFile, _downloadFile, value[4])
    ];
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pro: null;
} | {
    premium: null;
} | {
    basic: null;
}): SubscriptionPlan {
    return "pro" in value ? SubscriptionPlan.pro : "premium" in value ? SubscriptionPlan.premium : "basic" in value ? SubscriptionPlan.basic : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tradeTiming: null;
} | {
    positionSizing: null;
} | {
    riskManagement: null;
} | {
    emotionalControl: null;
} | {
    overtrading: null;
}): MistakeCategory {
    return "tradeTiming" in value ? MistakeCategory.tradeTiming : "positionSizing" in value ? MistakeCategory.positionSizing : "riskManagement" in value ? MistakeCategory.riskManagement : "emotionalControl" in value ? MistakeCategory.emotionalControl : "overtrading" in value ? MistakeCategory.overtrading : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    trial: null;
} | {
    expired: null;
} | {
    paid: _SubscriptionPlan;
}): {
    __kind__: "trial";
    trial: null;
} | {
    __kind__: "expired";
    expired: null;
} | {
    __kind__: "paid";
    paid: SubscriptionPlan;
} {
    return "trial" in value ? {
        __kind__: "trial",
        trial: value.trial
    } : "expired" in value ? {
        __kind__: "expired",
        expired: value.expired
    } : "paid" in value ? {
        __kind__: "paid",
        paid: from_candid_SubscriptionPlan_n16(_uploadFile, _downloadFile, value.paid)
    } : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _PendingPayment]>): Array<[Principal, PendingPayment]> {
    return value.map((x)=>from_candid_tuple_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MistakeEntry>): Array<MistakeEntry> {
    return value.map((x)=>from_candid_MistakeEntry_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _UserProfile, Array<_TradeEntry>, Array<_MistakeEntry>, [] | [_SubscriptionState]]>): Array<[Principal, UserProfile, Array<TradeEntry>, Array<MistakeEntry>, SubscriptionState | null]> {
    return value.map((x)=>from_candid_tuple_n29(_uploadFile, _downloadFile, x));
}
async function to_candid_ExternalBlob_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_MistakeCategory_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MistakeCategory): _MistakeCategory {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_SubscriptionPlan_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionPlan): _SubscriptionPlan {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Time | null): [] | [_Time] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MistakeCategory): {
    tradeTiming: null;
} | {
    positionSizing: null;
} | {
    riskManagement: null;
} | {
    emotionalControl: null;
} | {
    overtrading: null;
} {
    return value == MistakeCategory.tradeTiming ? {
        tradeTiming: null
    } : value == MistakeCategory.positionSizing ? {
        positionSizing: null
    } : value == MistakeCategory.riskManagement ? {
        riskManagement: null
    } : value == MistakeCategory.emotionalControl ? {
        emotionalControl: null
    } : value == MistakeCategory.overtrading ? {
        overtrading: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionPlan): {
    pro: null;
} | {
    premium: null;
} | {
    basic: null;
} {
    return value == SubscriptionPlan.pro ? {
        pro: null
    } : value == SubscriptionPlan.premium ? {
        premium: null
    } : value == SubscriptionPlan.basic ? {
        basic: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
